/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/tasks/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Tasks By User Id */
		get: operations['get_tasks_by_user_id_tasks__get'];
		put?: never;
		/** Create Task */
		post: operations['create_task_tasks__post'];
		/** Delete Tasks By User Id */
		delete: operations['delete_tasks_by_user_id_tasks__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/tasks/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete Task */
		delete: operations['delete_task_tasks__id__delete'];
		options?: never;
		head?: never;
		/** Update Task */
		patch: operations['update_task_tasks__id__patch'];
		trace?: never;
	};
	'/users/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete User */
		delete: operations['delete_user_users__id__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** @example 5eb7cf5a86d9755df3a6c593 */
		PydanticObjectId: string;
		/** Task */
		Task: {
			/** @description MongoDB document ObjectID */
			_id?: components['schemas']['PydanticObjectId'] | null;
			/** Title */
			title: string;
			/** Description */
			description: string;
			/**
			 * Completed
			 * @default false
			 */
			completed: boolean;
			/** User Id */
			user_id?: string | null;
			/**
			 * Urgent
			 * @default false
			 */
			urgent: boolean;
		};
		/** TaskUpdate */
		TaskUpdate: {
			/** Title */
			title?: string | null;
			/** Description */
			description?: string | null;
			/** Completed */
			completed?: boolean | null;
			/** User Id */
			user_id?: string | null;
			/** Urgent */
			urgent?: boolean | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_tasks_by_user_id_tasks__get: {
		parameters: {
			query?: never;
			header?: {
				userID?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Task'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_task_tasks__post: {
		parameters: {
			query?: never;
			header?: {
				userID?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['Task'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Task'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_tasks_by_user_id_tasks__delete: {
		parameters: {
			query?: never;
			header?: {
				userID?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_task_tasks__id__delete: {
		parameters: {
			query?: never;
			header?: {
				userID?: string;
			};
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_task_tasks__id__patch: {
		parameters: {
			query?: never;
			header?: {
				userID?: string;
			};
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['TaskUpdate'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Task'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_user_users__id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
